import XCTest
@testable import SumoKit

final class NetXMLParserTests: XCTestCase {
    private func tinyURL() throws -> URL {
        guard let url = Bundle.module.url(forResource: "tiny", withExtension: "net.xml", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: "tiny.net", withExtension: "xml", subdirectory: "Fixtures") else {
            throw XCTSkip("tiny.net.xml fixture missing")
        }
        return url
    }

    private func richURL() throws -> URL {
        guard let url = Bundle.module.url(forResource: "rich", withExtension: "net.xml", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: "rich.net", withExtension: "xml", subdirectory: "Fixtures") else {
            throw XCTSkip("rich.net.xml fixture missing")
        }
        return url
    }

    func testParsesTinyNetwork() throws {
        let g = try NetXMLParser.parse(url: try tinyURL())
        XCTAssertEqual(g.edges.count, 2 + 1)   // e1, e2 plus internal :j1_0 generated by netconvert
        XCTAssertEqual(g.junctions.count, 3)
        XCTAssertGreaterThan(g.lanes.count, 0)
        XCTAssertGreaterThan(g.laneShapePoints.count, 0)

        XCTAssertNotNil(g.edgeIndex["e1"])
        XCTAssertNotNil(g.edgeIndex["e2"])
        XCTAssertNotNil(g.junctionIndex["j0"])
        XCTAssertNotNil(g.junctionIndex["j1"])
        XCTAssertNotNil(g.junctionIndex["j2"])

        let e1 = g.edges[Int(g.edgeIndex["e1"]!)]
        XCTAssertEqual(e1.fromJunction, "j0")
        XCTAssertEqual(e1.toJunction, "j1")
        XCTAssertEqual(e1.laneRange.count, 1)

        let lane = g.lanes[Int(e1.laneRange.lowerBound)]
        XCTAssertEqual(lane.id, "e1_0")
        XCTAssertGreaterThan(lane.length, 90)
        XCTAssertEqual(g.location.projParameter, "!")
        XCTAssertEqual(g.location.convBoundary, SIMD4<Double>(0, 0, 200, 0))
        XCTAssertEqual(Array(g.laneShape(lane)).first, SIMD2<Float>(0, -1.6))
        XCTAssertEqual(g.bounds(), SIMD4<Float>(0, -3.2, 200, 0))
    }

    func testParsesTrafficLightRoundaboutAndConnectionMetadata() throws {
        let g = try NetXMLParser.parse(url: try richURL())
        XCTAssertEqual(g.roundabouts.count, 1)
        XCTAssertEqual(g.roundabouts[0].nodes, ["j0", "j1", "j2"])
        XCTAssertEqual(g.roundabouts[0].edges, ["a", "b"])

        XCTAssertEqual(g.tlLogics.count, 1)
        XCTAssertEqual(g.tlLogics[0].id, "j1")
        XCTAssertEqual(g.tlLogics[0].type, "static")
        XCTAssertEqual(g.tlLogics[0].offset, 3)
        XCTAssertEqual(g.tlLogics[0].phases.count, 2)
        XCTAssertEqual(g.tlLogics[0].phases[0].minDuration, 10)
        XCTAssertEqual(g.tlLogics[0].phases[0].maxDuration, 60)

        XCTAssertEqual(g.connections.count, 1)
        XCTAssertEqual(g.connections[0].trafficLightID, "j1")
        XCTAssertEqual(g.connections[0].linkIndex, 0)
        XCTAssertEqual(g.polygons.count, 1)
        XCTAssertEqual(g.polygons[0].id, "zone0")
        XCTAssertEqual(g.polygons[0].color, SumoColor(red: 60, green: 140, blue: 95, alpha: 180))
        XCTAssertEqual(Array(g.polygonShape(g.polygons[0])).count, 4)
        XCTAssertEqual(g.pois.count, 1)
        XCTAssertEqual(g.pois[0].id, "poi0")
        XCTAssertEqual(g.pois[0].position, SIMD2<Float>(50, 5))

        let junction = g.junctions[Int(g.junctionIndex["j1"]!)]
        XCTAssertEqual(junction.incomingLanes, ["a_0"])
        XCTAssertEqual(junction.internalLanes, [":j1_0_0"])
        XCTAssertEqual(junction.bounds, SIMD4<Float>(49, -1, 51, 1))
    }

    func testQuadtreeFindsEdgesByViewport() throws {
        let g = try NetXMLParser.parse(url: try tinyURL())
        let qt = g.makeSpatialIndexes().edges
        var hits = Set<Int32>()
        // Box covering only the second half of the road.
        qt.query(in: SIMD4(110, -5, 220, 5)) { hits.insert($0) }
        XCTAssertTrue(hits.contains(g.edgeIndex["e2"]!))
        XCTAssertFalse(hits.contains(g.edgeIndex["e1"]!))
    }

    func testSpatialIndexesCoverLanesEdgesAndJunctionsAndFilterInternalEdges() throws {
        let g = try NetXMLParser.parse(url: try tinyURL())

        let external = g.makeSpatialIndexes()
        let all = g.makeSpatialIndexes(includeInternalEdges: true)

        let wholeNetwork = SIMD4<Float>(-10, -10, 210, 10)
        let externalEdges = Set(external.edges.query(in: wholeNetwork).map { g.edges[Int($0)].id })
        let allEdges = Set(all.edges.query(in: wholeNetwork).map { g.edges[Int($0)].id })
        let laneIDs = Set(external.lanes.query(in: wholeNetwork).map { g.lanes[Int($0)].id })
        let tightLaneIDs = Set(external.lanes.query(in: SIMD4<Float>(0, -1.6, 200, -1.6)).map { g.lanes[Int($0)].id })
        let junctionIDs = Set(external.junctions.query(in: wholeNetwork).map { g.junctions[Int($0)].id })

        XCTAssertTrue(externalEdges.contains("e1"))
        XCTAssertTrue(externalEdges.contains("e2"))
        XCTAssertFalse(externalEdges.contains(":j1_0"))
        XCTAssertTrue(allEdges.contains(":j1_0"))
        XCTAssertTrue(laneIDs.contains("e1_0"))
        XCTAssertTrue(laneIDs.contains("e2_0"))
        XCTAssertTrue(tightLaneIDs.contains("e1_0"))
        XCTAssertTrue(tightLaneIDs.contains("e2_0"))
        XCTAssertTrue(junctionIDs.isSuperset(of: ["j0", "j1", "j2"]))
    }

    func testGraphFallsBackToContentBoundsWhenDeclaredBoundaryIsInvalid() {
        let graph = NetGraph()
        graph.location.convBoundary = SIMD4(50, 0, 10, 0)
        graph.edges.append(Edge(
            id: "e",
            fromJunction: "a",
            toJunction: "b",
            function: .normal,
            priority: 1,
            laneRange: 0..<0,
            bounds: SIMD4(10, -2, 50, 2)
        ))

        XCTAssertEqual(graph.bounds(), SIMD4<Float>(10, -2, 50, 2))
    }

    func testQuadtreeDoesNotDuplicateEntriesThatSpanChildCells() {
        let qt = Quadtree<Int32>(bounds: SIMD4(0, 0, 100, 100), leafCapacity: 1, maxDepth: 4)
        qt.insert(.init(payload: 1, bounds: SIMD4(10, 10, 20, 20)))
        qt.insert(.init(payload: 2, bounds: SIMD4(40, 40, 60, 60)))
        qt.insert(.init(payload: 3, bounds: SIMD4(80, 80, 90, 90)))

        let hits = qt.query(in: SIMD4(0, 0, 100, 100))
        XCTAssertEqual(hits.filter { $0 == 2 }.count, 1)
    }
}
